create table if not exists public.ai_feedback (
  id bigint generated by default as identity primary key,
  text text not null,
  label text not null,
  source text not null default 'liquidador',
  confirmed boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists ai_feedback_label_idx on public.ai_feedback(label);
create index if not exists ai_feedback_created_at_idx on public.ai_feedback(created_at);

alter table public.ai_feedback enable row level security;

-- The browser only needs INSERT through the AI Engine API. Do not expose the
-- Supabase service-role key in the Liquidador frontend.
-- Keep SELECT/UPDATE/DELETE unavailable to anon/authenticated roles.


-- v0.7.1: lifecycle for processed learning examples
alter table public.ai_feedback
  add column if not exists processed_at timestamptz null,
  add column if not exists training_run_id text null,
  add column if not exists retained boolean not null default false;

create index if not exists ai_feedback_pending_idx
  on public.ai_feedback(processed_at, confirmed);

create index if not exists ai_feedback_retained_idx
  on public.ai_feedback(retained, label, id);
